# Generated by Django 4.2.2 on 2023-06-29 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_userpublickey_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpublickey',
            old_name='public_key',
            new_name='key',
        ),
        migrations.AlterField(
            model_name='userpublickey',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pub', to=settings.AUTH_USER_MODEL),
        ),
    ]
